ignoreRegExpList:
  - /cooldown(s)?/i
  - /snackbar(s)?/i
words:
  - orbitron
  - pressable
  - supabase
  - usehooks
  - Voidrunner
  - worklets
  # API specific terms
  - BIOCOMPOSITES
  - FEBA
  - HOLOGRAPHICS
  - HYPERGIANT
  - MERITIUM
  - MICROABRASIONS
  - POLYNUCLEOTIDES
  - SUPERGRAINS
  - SUPERVOLCANOES
  - URANITE
  # Misspelled words in API specs
  - exterier
  - Symbo
